# Numpy

NumPy, which stands for Numerical Python, 
is a library consisting of multidimensional array objects and a collection of routines for processing those arrays. 
Using NumPy, mathematical and logical operations on arrays can be performed. 
NumPy is a Python package.

NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

In [1]:
#import numpy 
import numpy as np

# 3 benefits of array over lists

1.Less memory        
2.Fast           
3.Convenient

In [2]:
#numpy consume less memory
import sys
array=np.arange(1000)
lst=[x for x in range(1000)]
print("Size of numpy array : ",array.size*array.itemsize)
print("Size of list : ",sys.getsizeof(lst[1])*len(lst))

Size of numpy array :  4000
Size of list :  28000


In [3]:
#Numpy is faster
import time
array1=np.arange(1000000)
array2=np.arange(1000000)
lst1=range(1000000)
lst2=range(1000000)
start1=time.time()
result=[(x+y) for x,y in zip(lst1,lst2)]
print("Time for lists : ",(time.time()-start1)*1000)
start2=time.time()
result2=array1+array2
print("Time for numpy : ",(time.time()-start2)*1000)

Time for lists :  351.9716262817383
Time for numpy :  17.774343490600586


In [4]:
#numpy is convinient
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
print("a+b :",a+b)
print("a-b :",a-b)
print("a*b :",a*b)
print("a/b :",a/b)

a+b : [ 7  9 11 13 15]
a-b : [-5 -5 -5 -5 -5]
a*b : [ 6 14 24 36 50]
a/b : [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [5]:
#Single dimensional array
n1=np.array([4,52,3,62,3,36,5])
n1
type(n1)

numpy.ndarray

In [8]:
#creating a NumPy array with 2 dimensions
n1=np.array([4,52,3,62,3,36,5],ndmin=2)
n1,n1.shape

(array([[ 4, 52,  3, 62,  3, 36,  5]]), (1, 7))

In [9]:
#multi dimensional array
n2=np.array([[45,26,25,6,57],[55,53,54,23,54]])
n2
type(n2),n2.shape

(numpy.ndarray, (2, 5))

In [10]:
#converting elements from intergers to float in numpy array
n2=np.array([[45,26,25,6,57],[55,53,54,23,54]],dtype=np.float64)
n2

array([[45., 26., 25.,  6., 57.],
       [55., 53., 54., 23., 54.]])

In [11]:
#another way of converting elements from intergers to float in numpy array
n2=np.array([[45,26,25,6,57],[55,53,54,23,54]],dtype=float)
n2

array([[45., 26., 25.,  6., 57.],
       [55., 53., 54., 23., 54.]])

In [12]:
#converting elements from intergers to complex in numpy array
n2=np.array([[45,26,25,6,57],[55,53,54,23,54]],dtype=complex)
n2

array([[45.+0.j, 26.+0.j, 25.+0.j,  6.+0.j, 57.+0.j],
       [55.+0.j, 53.+0.j, 54.+0.j, 23.+0.j, 54.+0.j]])

In [13]:
#Create an array with data type string

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [14]:
#creating a new array with another datatype
arr = np.array([0,1, 2,0, 3, 4])
newarr=arr.astype(bool)
print(newarr)

[False  True  True False  True  True]


In [15]:
#Accessing elements in 2-D array
n2=np.array([[45,26,25,6,57],[55,53,54,23,54]])
n2[1][3] #accessing 23

23

In [17]:
#negative indexing
n2=np.array([[45,26,25,6,57],[55,53,54,23,54]])
n2[1,-1] #accesing last element from second array
#n2[1][-1] can also be used

54

In [18]:
#initializing array with zeroes
n3=np.zeros((5,6))
n3

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
n3[1][1]=1.
n3

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [20]:
#initializing array with particular value
n4=np.full((8,5),69)
n4

array([[69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69]])

In [21]:
#linspace() will generate specified number of elements with a given range which are linearly spaced
array=np.linspace(10,20,15)
array

array([10.        , 10.71428571, 11.42857143, 12.14285714, 12.85714286,
       13.57142857, 14.28571429, 15.        , 15.71428571, 16.42857143,
       17.14285714, 17.85714286, 18.57142857, 19.28571429, 20.        ])

In [22]:
#getting a range of values using arange function
n5=np.arange(5,45)
n5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44])

In [23]:
#getting a range of values with step
n6=np.arange(10,100,5)
n6

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [24]:
#getting a random number from a given range
n7=np.random.randint(10,100)
n7


90

In [25]:
#getting multiple random numbers from a given range
lst=[]
for i in range(10):
    n=np.random.randint(1,100)
    lst.append(n)
lst

[7, 86, 36, 25, 30, 36, 69, 76, 3, 99]

In [26]:
#creating array using arange
arr=np.arange(5,20)
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [27]:
#creating 2-D array using arange
arr=np.arange(5,20).reshape(3,5)
arr

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [28]:
#getting multiple random numbers from a given range
n8=np.random.randint(10,100,10)
n8

array([44, 99, 70, 17, 82, 39, 85, 18, 31, 58])

In [29]:
#getting given number of values with given standard deviation
#random.normal(loc=0.0, scale=1.0, size=None)
lst=np.random.normal(150,15,50) # 50 values are generated with standard deviation 15 concentrating around 150
lst

array([136.40189234, 134.25104938, 150.69356197, 156.54405882,
       145.08260472, 135.71608842, 148.809571  , 126.96822489,
       137.7227329 , 139.24473013, 172.44771684, 131.65388142,
       167.64921951, 158.48217683, 111.55567043, 131.55329843,
       141.56962773, 143.03644003, 149.78101973, 135.55460823,
       148.3757636 , 137.10764341, 137.38761406, 171.20616315,
       142.35613545, 177.40434893, 134.71202612, 153.91148083,
       172.71773181, 188.35583136, 161.82933978, 133.95881482,
       153.17938782, 145.04119175, 146.66998102, 155.52651838,
       147.28623008, 165.87655564, 144.69579436, 160.88548133,
       151.05301998, 146.1978674 , 142.17519395, 158.0229569 ,
       159.39960618, 175.24076065, 160.33688531, 153.52218853,
       144.92110004, 160.09466305])

In [30]:
#generating random values with provide m*n matrix
lst=np.random.randn(5,4)
lst

array([[ 0.84700361,  1.15585091, -0.28192104,  0.05950705],
       [ 1.09504236,  1.88920723,  0.24632337, -0.09427837],
       [-0.8386103 , -0.40085658, -0.0954649 , -0.2078219 ],
       [-0.63455347,  1.38741112, -1.16531605,  1.06628607],
       [-0.33093781,  1.95933885, -0.29673598,  0.88079574]])

In [31]:
#shape() to get the shape of an array
n9=np.array([[45,26,2,5,45,6],[25,1,63,5,74,12]])
np.shape(n9)

(2, 6)

In [32]:
#n9.shape or np.shape(n9) -> both way will work
n9.shape

(2, 6)

In [33]:
#shape() to set the shape of an array
n9.shape=(4,3)
n9

array([[45, 26,  2],
       [ 5, 45,  6],
       [25,  1, 63],
       [ 5, 74, 12]])

In [34]:
#ravel() will convert multidimensional array to single dimension
#it will just return the new array but does not effect original array
n9=np.array([[45,26,2,5,45,6],[25,1,63,5,74,12]])
n9.ravel()

array([45, 26,  2,  5, 45,  6, 25,  1, 63,  5, 74, 12])

In [35]:
array=np.arange(20).reshape(4,5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [36]:
#normal way of iterating through all elements
for row in array:
    for element in row:
        print(element)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [37]:
#iterating throught every element using "flat" method
# array.flatten() can also be used
for element in array.flat:
    print(element)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [38]:
array=np.arange(15).reshape(3,5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [39]:
##iteration using nditer(row wise)
for element in np.nditer(array,order="C"):#c => C order
    print(element)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [40]:
#column wise iteration
for element in np.nditer(array,order="F"):#F => Fortran order
    print(element)

0
5
10
1
6
11
2
7
12
3
8
13
4
9
14


In [41]:
#grouping elements column wise
for element in np.nditer(array,order="F",flags=["external_loop"]):
    print(element)

[ 0  5 10]
[ 1  6 11]
[ 2  7 12]
[ 3  8 13]
[ 4  9 14]


In [42]:
#squaring every element in an array using op_flags
for element in np.nditer(array,op_flags=["readwrite"]):
    element[...]=element*element
array

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

In [43]:
#iterating through multiple arrays simultaneously
array1=np.arange(9).reshape(3,3)
array2=np.arange(10,13).reshape(3,1)
array1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [44]:
array2

array([[10],
       [11],
       [12]])

In [45]:
#conditions
#1. m and n order should be same or m or n should be same while other order is 1
for x,y in np.nditer((array1,array2)):
    print(x,y)

0 10
1 10
2 10
3 11
4 11
5 11
6 12
7 12
8 12


In [46]:
#vstack is used to add mutiple arrays into single array vertically
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
np.vstack((arr1,arr2))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [47]:
#hstack is used to merge multiple arrays to single array horizontally
np.hstack((arr1,arr2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
#column_stack is used to merge the colums of an multiple arrays
array1=np.arange(0,6).reshape(2,3)
array2=np.arange(6,12).reshape(2,3)
array1

array([[0, 1, 2],
       [3, 4, 5]])

In [49]:
array2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [50]:
np.column_stack((array1,array2))

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [51]:
#splitting array
array=np.arange(10).reshape(2,5)
array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [52]:
#Splitting an array horizontally
np.hsplit(array,5)

[array([[0],
        [5]]),
 array([[1],
        [6]]),
 array([[2],
        [7]]),
 array([[3],
        [8]]),
 array([[4],
        [9]])]

In [53]:
#Splitting an array vertically
np.vsplit(array,2)

[array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]])]

In [54]:
#numpy intersection
arr3=np.array([1,2,3,4,5,6])
arr4=np.array([4,5,6,7,8,9])
np.intersect1d(arr3,arr4)

array([4, 5, 6])

In [55]:
#numpy differece of two arrays
np.setdiff1d(arr3,arr4)

array([1, 2, 3])

In [56]:
#getting sum of elements in an array
arr5=np.array([10,20,30])
np.sum(arr5)

60

In [57]:
arr6=np.array([40,50,60])
arr6.sum()

150

In [58]:
#sum of elements from two arrays
np.sum((arr5,arr6))

210

In [59]:
#sum of columns from two arrays
np.sum((arr5,arr6),axis=0)


array([50, 70, 90])

In [60]:
#sum of rows from two arrays
np.sum((arr5,arr6),axis=1)

array([ 60, 150])

In [61]:
#fetching minimum value from two arrays
np.min((arr5,arr6))

10

In [62]:
#maximum value from two arrays
np.max((arr5,arr6))

60

In [63]:
#Sqare root for all elements of an array
#arr5.sqrt() doesn't work
np.sqrt(arr5)

array([3.16227766, 4.47213595, 5.47722558])

In [64]:
#adding 1 to every element of arr5
arr5=arr5+1
arr5

array([11, 21, 31])

In [65]:
#subtracting 1 from every element of arr5
arr5=arr5-1
arr5

array([10, 20, 30])

In [66]:
#multiplying 2 with every element of arr5
arr5=arr5*2
arr5

array([20, 40, 60])

In [67]:
#dividing every element of arr5 with 2
arr5=arr5/2
arr5

array([10., 20., 30.])

In [68]:
arr=np.array([10,20,30,40,50])

In [69]:
#mean
np.mean(arr)

30.0

In [70]:
#median
np.median(arr)

30.0

In [71]:
#standard deviation
np.std(arr)

14.142135623730951

In [72]:
arr9=np.array([[10,20,30],[40,50,60],[70,80,90]])
arr9

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [73]:
#extracing rows
arr9[1,:]

array([40, 50, 60])

In [74]:
#extraction columns
arr9[:,1]

array([20, 50, 80])

In [75]:
#Transpose a matrix
np.transpose(arr9)

array([[10, 40, 70],
       [20, 50, 80],
       [30, 60, 90]])

In [76]:
arr8=np.array([[90,80,70],[60,50,40],[30,20,10]])
arr8

array([[90, 80, 70],
       [60, 50, 40],
       [30, 20, 10]])

In [77]:
#multiplication of two multidimensional arrays
arr8.dot(arr9)

array([[ 9000, 11400, 13800],
       [ 5400,  6900,  8400],
       [ 1800,  2400,  3000]])

In [78]:
#saving a numpy array
np.save("my_numpy_array",arr8)

In [79]:
#loading a numpy array
numpy_array=np.load("my_numpy_array.npy")

In [80]:
numpy_array

array([[90, 80, 70],
       [60, 50, 40],
       [30, 20, 10]])

In [81]:
#Indexing with boolean array
array=np.random.randint(10,50,20).reshape(4,5)
array

array([[10, 29, 44, 49, 13],
       [16, 22, 48, 23, 25],
       [37, 31, 38, 36, 42],
       [30, 33, 34, 18, 32]])

In [82]:
temp=array>25
temp

array([[False,  True,  True,  True, False],
       [False, False,  True, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True, False,  True]])

In [83]:
array[temp]

array([29, 44, 49, 48, 37, 31, 38, 36, 42, 30, 33, 34, 32])

In [84]:
#another way
array[array>25]

array([29, 44, 49, 48, 37, 31, 38, 36, 42, 30, 33, 34, 32])

# copying an array

In [85]:
#copying array using "copy"
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [86]:
#copying array using "view"
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [87]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
import numpy as np
lst=input().split(" ")
a=int(lst[0])
b=int(lst[1])
arr=np.zeros((a,b))
for i in range(a):
    for j in range(b):
        if i==j:
            arr[i][j]=1.
print(arr)

3 3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [88]:
import numpy
arr=input().split(" ")
a=int(arr[0])
b=int(arr[1])
arr=numpy.eye(a,b,k=0)
print(arr)

3 3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
